name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run lint

  test:
    name: Tests (Node.js ${{ matrix.node }})

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node:
          - '10'
          - '11'
          - '12'
          - '14'
          - '16'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
